import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";

export default defineConfig({
  base: "/motif-music/",

  plugins: [
    react(),

    VitePWA({
      registerType: "autoUpdate",

      // Registered manually via UpdateContext.jsx
      injectRegister: false,

      // These are generated by scripts/generate-icons.mjs
      includeAssets: ["icons/*.svg", "icons/*.png"],

      manifest: {
        id: "/motif-music/",

        name: "Motif — Local-First Music",
        short_name: "Motif",

        description:
          "Your library, not a subscription. Local-first music player and discovery.",

        theme_color: "#000000",
        background_color: "#000000",

        display: "standalone",

        display_override: [
          "window-controls-overlay",
          "standalone",
          "minimal-ui",
        ],

        orientation: "portrait",

        start_url: "/motif-music/",
        scope: "/motif-music/",

        categories: ["music", "audio", "entertainment", "utilities"],

        icons: [
          {
            src: "icons/icon-192.png",
            sizes: "192x192",
            type: "image/png",
            purpose: "any",
          },
          {
            src: "icons/icon-512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "any",
          },
          {
            src: "icons/icon-maskable-512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],

        screenshots: [
          {
            src: "screenshots/home.png",
            sizes: "1080x1920",
            type: "image/png",
            form_factor: "narrow",
            label: "Home library",
          },
          {
            src: "screenshots/now-playing.png",
            sizes: "1080x1920",
            type: "image/png",
            form_factor: "narrow",
            label: "Now Playing",
          },
          {
            src: "screenshots/library-desktop.png",
            sizes: "1920x1080",
            type: "image/png",
            form_factor: "wide",
            label: "Desktop library",
          },
        ],

        shortcuts: [
          {
            name: "Library",
            short_name: "Library",
            url: "/motif-music/#/library",
          },
          {
            name: "Search",
            short_name: "Search",
            url: "/motif-music/#/search",
          },
          {
            name: "Now Playing",
            short_name: "Player",
            url: "/motif-music/#/player",
          },
        ],

        launch_handler: {
          client_mode: ["focus-existing", "auto"],
        },

        file_handlers: [
          {
            action: "/motif-music/",
            accept: {
              "audio/*": [
                ".mp3",
                ".flac",
                ".m4a",
                ".aac",
                ".ogg",
                ".opus",
                ".wav",
              ],
            },
          },
        ],
      },

      workbox: {
        globPatterns: ["**/*.{js,css,html,png,svg,ico,webmanifest}"],

        cleanupOutdatedCaches: true,
        clientsClaim: true,
        skipWaiting: true,
      },
    }),
  ],

  server: {
    host: true,
    port: 5173,
  },

  build: {
    target: "es2022",
    sourcemap: true,
  },
});
